services:

  service:
    container_name: auth_service
    build:
      context: src
      dockerfile: ./rest/Dockerfile
    environment:
      - FLASK_APP=src/rest/app.py
    entrypoint: >
      sh -c "python -m flask run --host 0.0.0.0 --port 8000 --debugger"
    expose:
      - "8000"
    env_file:
      - ./src/config/.env
    depends_on:
      - db
    networks:
      - default

  auth_grpc:
    container_name: auth_grpc
    build:
      context: src
      dockerfile: ./grpc_api/Dockerfile
    entrypoint: >
      sh -c "python src/grpc_api/main.py"
    env_file:
      - ./src/config/.env
    ports:
      - "50051:50051"
    depends_on:
      - db
      - service
    networks:
      - default

  nginx:
    container_name: nginx_auth
    build:
      context: ./src/nginx
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - service
      - auth_grpc
    networks:
      - default

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  redis:
    container_name: redis
    build:
      context: ./src/redis
      dockerfile: ./Dockerfile
    depends_on:
      - service
    ports:
      - "6379:6379"

  db:
    container_name: db_auth
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/config/.env
    ports:
      - "5431:5432"

volumes:
  postgres_data:


networks:
  default:
    external:
      name: movies_network