services:

  service:
    container_name: auth_service
    build:
      context: src
      dockerfile: ./app/Dockerfile
    environment:
      - FLASK_APP=src/app/app.py
    entrypoint: >
      sh -c "python -m flask run --host 0.0.0.0 --port 8000 --debugger"
    expose:
      - "8000"
    env_file:
      - ./src/app/config/.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: ./src/nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - service

  redis:
    container_name: redis
    build:
      context: ./src/redis
      dockerfile: ./Dockerfile
    depends_on:
      - service
    ports:
      - "6379:6379"

  db:
    container_name: db_postgres
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/app/config/.env

volumes:
  postgres_data:


