# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_check_pb2 as user__check__pb2


class CheckAuthUserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAuthInfo = channel.unary_unary(
                '/checkuser.CheckAuthUser/GetAuthInfo',
                request_serializer=user__check__pb2.CheckUserRequest.SerializeToString,
                response_deserializer=user__check__pb2.CheckUser.FromString,
                )


class CheckAuthUserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAuthInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckAuthUserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAuthInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthInfo,
                    request_deserializer=user__check__pb2.CheckUserRequest.FromString,
                    response_serializer=user__check__pb2.CheckUser.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'checkuser.CheckAuthUser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CheckAuthUser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAuthInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/checkuser.CheckAuthUser/GetAuthInfo',
            user__check__pb2.CheckUserRequest.SerializeToString,
            user__check__pb2.CheckUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
